//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterClass
    {
        public int CharacterClassID { get; set; }
        public int CharacterID { get; set; }
        public int ClassID { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Class Class { get; set; }
    }
}
