//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterDescription
    {
        public int CharacterDescriptionID { get; set; }
        public int CharacterID { get; set; }
        public int DescriptionID { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Description Description { get; set; }
    }
}
