//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int CampaignID { get; set; }
        public string Fullname { get; set; }
        public int OwnerID { get; set; }
        public int UniverseID { get; set; }
        public int PlanetID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsOpen { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Planet Planet { get; set; }
        public virtual Universe Universe { get; set; }
    }
}
