//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterItem
    {
        public int CharacterItemID { get; set; }
        public int CharacterID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Item Item { get; set; }
    }
}
