//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public int PermissionTypeID { get; set; }
        public int GrantingUserID { get; set; }
        public int GrantedUserID { get; set; }
        public int ContentTypeID { get; set; }
        public int ContentID { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual PermissionType PermissionType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
